variables:
  - name: name
    value: "hover"
  - name: version
    value: "0.5.3a"

package:
  name: ${{ variables.name|lower }}
  version: ${{ variables.version }}

source:
  git_url: https://github.com/phurwicz/hover

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - bokeh >=2.3.3
    - scikit-learn >=0.20.0
    - pytorch >=1.4.0
    - pandas >=1.3.0
    - numpy >=1.14
    - scipy >=1.3.2
    - tqdm >=4.0
    - rich >=11.0.0
    - umap-learn >=0.3.10

test:
  imports:
    - hover
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://phurwicz.github.io/hover
  license: MIT
  license_file: LICENSE
  summary: Label data at scale. Fun and precision included.
  dev_url: https://github.com/phurwicz/hover

extra:
  recipe-maintainers:
    - phurwicz
    - haochuanwei
