# This workflow will build the latest source files in Anaconda.

name: Cross-OS Conda Build

on:
  schedule:
    - cron: "0 0 * * 1,4"
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9']
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Conda build
        run: |
          conda build --output-folder ./conda-out/ ./conda-recipe/
