# This workflow will install Python dependencies and run tests on the source code.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Cross-OS Source Test

on:
  schedule:
    - cron: "0 0 * * 1,4"
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9']
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Find cached env
      id: find-venv
      uses: actions/cache@v2
      with:
        path: env
        key: ${{ runner.os }}-${{ runner.python-version }}-venv-test-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.python-version }}-venv-test-

    - name: Create env
      id: create-venv
      if: steps.find-venv.outputs.cache-hit != 'true'
      run: |
        python -m venv env

    - name: Get dependencies and test
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ] || [ "$RUNNER_OS" == "macOS" ]; then
             source env/bin/activate
        elif [ "$RUNNER_OS" == "Windows" ]; then
             ./env/Scripts/activate
        else
             echo "$RUNNER_OS not supported"
             exit 1
        fi
        pip install --upgrade pip
        pip install --upgrade tox tox-gh-actions
        tox -e test_api
