# This workflow will install Python dependencies and run tests on the code snippets included in the documentation.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Documentation Script Test

on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches: [ main ]
    paths:
      - 'docs/**.*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  doc-script:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9']
        os: [ubuntu-latest]

    steps:
    - name: Clone hover
      uses: actions/checkout@v2

    - name: Clone hover-binder
      uses: actions/checkout@v2
      with:
        repository: phurwicz/hover-binder
        ref: master
        path: .hover-binder

    - name: Pick local library from Binder repo
      run: |
        cp -r .hover-binder/local_lib ./local_lib
        rm -rf .hover-binder

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Non-Python Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsndfile1

    - name: Test with Tox
      run: |
        pip install --upgrade pip
        pip install --upgrade tox tox-gh-actions
        git branch pipeline/notebook-generation
        git checkout pipeline/notebook-generation
        git pull
        git merge main --commit
        tox -e test_doc_scripts

    - name: Update Generated Notebooks
      run: |
        git config --global user.name ${{ secrets.ACTIONS_GIT_USERNAME }}
        git config --global user.email ${{ secrets.ACTIONS_GIT_EMAIL }}
        git add docs/pipelines/generated/*.ipynb
        git commit -m "Automatic update of notebooks generated from documentation scripts"
        git push
