# This workflow will install Python dependencies and run tests on the code snippets included in the documentation.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Documentation Script Test

on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches: [ main ]
    paths:
      - 'docs/**.*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9']
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Test with Tox
      run: |
        pip install --upgrade pip
        pip install --upgrade tox tox-gh-actions
        tox -e test_doc_scripts
