# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: python-package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.6.11', '3.7.10', '3.8.8']
        os: [ubuntu-latest]
        # 12/14/2020: disabling macos during builds, but it should install ok
        #os: [macos-10.15, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Find cached env
      id: find-venv
      uses: actions/cache@v2
      with:
        path: env
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Create env
      id: create-venv
      if: steps.find-venv.outputs.cache-hit != 'true'
      run: |
        python -m venv env

    - name: Activate env
      id: activate-venv
      run: |
        source env/bin/activate

    - name: Get installation dependencies
      if: steps.find-venv.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        # dependencies that could be involved in builds
        pip install pip-tools setuptools wheel cython
        # find dependencies based on setup.py
        pip-compile
        pip install -r requirements.txt

    - name: Install hover
      run: python setup.py install

    - name: Get testing dependencies
      if: steps.find-venv.outputs.cache-hit != 'true'
      run: pip install tox tox-gh-actions

    - name: Test and make coverage report
      run: tox -e test_api

    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: cobertura.xml
